### ISSUE TITLE
SEO and Image modules

### ISSUE THREAD

**Issue by sean-au** [gethyas/seo#1]
Hi there

Just letting you know I have authored some hugo modules

They may help your hyas project (including them), or you may get some ideas from them

https://github.com/future-wd/hugo-seo
https://github.com/future-wd/hugo-responsive-images
https://github.com/future-wd/hugo-inline-svg

and under development
https://github.com/future-wd/hugo-responsive-background-images

**Comment by h-enk** [comment]
Thanks for letting me know — Hyas is currently using the following integrations (npm modules):

- [Hyas SEO](https://github.com/gethyas/seo)
- [Hyas Images](https://github.com/gethyas/images)
- [Hyas Inline SVG](https://github.com/gethyas/inline-svg)
