### ISSUE TITLE
Hardcoded `cover.png`

### ISSUE THREAD

**Issue by salim-b** [gethyas/seo#11]
In latest [`seo/opengraph.html` partial](https://github.com/gethyas/seo/blob/main/layouts/partials/seo/opengraph.html) the image file path `assets/cover.png` is hardcoded. This results in the following warnings if the file doesn't exist:

```
WARN  [Hugo SEO] Missing default image for og:image - assets/cover.png does not exist. Use a high-quality image with dimensions of at least 1200 x 630 pixels, while keeping the file size under 8 MB.
WARN  [Hugo SEO] Missing default image for og:image - Add 'images: ['cover.png']' to your hugo.yaml
```

Why would you instruct the user to set `images: ['cover.png']` in their `hugo.yaml` when `cover.png` is **hardcoded** in the partial? And why would you hardcode the image file path in the first place?

Also I have a hard time to understand the purpose of the the first 11 lines:

https://github.com/gethyas/seo/blob/903b0e4d9da38d18bb9740141cef4babd28ab10f/layouts/partials/seo/opengraph.html#L1-L11

Maybe you could shed some light on this @h-enk ? Thanks!

**Comment by h-enk** [comment]
I agree that there's room for improvement — to be picked up in a next round

**Comment by h-enk** [comment]
Together w/ https://github.com/gethyas/seo/issues/9

**Comment by h-enk** [comment]
Dropped the lines w/ [v2.2.0](https://github.com/gethyas/seo/releases/tag/v2.2.0) — now fully in line w/ Hugo's template (no warning if a user forgot to add an image)

Maybe re-adding it at a later date, but making it flexible — like how it's done with [favicons](https://github.com/gethyas/seo/blob/main/layouts/partials/seo/favicons.html)
