### ISSUE TITLE
Hyas SEO v2 twitter:image path problem

### ISSUE THREAD

**Issue by h-enk** [gethyas/seo#16]
### Discussed in https://github.com/orgs/gethyas/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **pensivedog** December 22, 2023</sup>
After upgrading the hyas seo module from v1 to v2, the twitter image path is incorrect. Instead of using, for instance:

`localhost:1313/articles/article-title/article-image.jpg` for the twitter image, it now uses

`localhost:1313/article-image.jpg`, placing the file name directly after the site root, without the rest of the file path.

Any idea how to fix this?</div>

**Comment by razonyang** [comment]
What does the content structure looks like? I guess that the `article-image.jpg` isn't a image resource of the `article-title`.

**Comment by h-enk** [comment]
No, I tested/confirmed this. I suspect it's got something to do with [the context and the dot](https://www.regisphilibert.com/blog/2018/02/hugo-the-scope-the-context-and-the-dot/)

**Comment by h-enk** [comment]
Frontmatter referenced image:

```md
images: ["vincent-van-zalinge-9NapHjhwxEg-unsplash.jpg"]
```

Page bundle:

```bash
│
└───doks-1-2
        cover-doks-1-2.png
        index.md
        vincent-van-zalinge-9NapHjhwxEg-unsplash.jpg
```

Output:

```html
<meta property="og:image" content="http://localhost:1313/vincent-van-zalinge-9NapHjhwxEg-unsplash.jpg" />
```

Should be:

```html
<meta property="og:image" content="http://localhost:1313/blog/doks-1-2/vincent-van-zalinge-9NapHjhwxEg-unsplash.jpg" >
```

**Comment by razonyang** [comment]
I still couldn't reproduce it with this repo on both of Linux (WSL2 Ubuntu) and Windows.

Hugo version: v0.121.1

![image](https://github.com/gethyas/seo/assets/17720932/df52f8de-e184-465e-a233-0230076e7e69)

I think there should be something else cause this issue, perhaps running on wrong Hugo version (this changes was introduced since v0.121.0) or others.

**Comment by h-enk** [comment]
> [..] this changes was introduced since v0.121.0 [..]

Ah, I missed that — thanks!

I can confirm it does work all right with:

```json
  "otherDependencies": {
    "hugo": "0.121.1"
  },
```

**Comment by pensivedog** [comment]
So we should manually add this to our package.json -- is that the right way to fix this?

**Comment by h-enk** [comment]
That won't work right now. But, it will work with the upcoming Doks (and Hyas) release that will surface the most important dependencies, so you can update Hugo, Images, and SEO for example —  yourself.

**Comment by h-enk** [comment]
Available soon

**Comment by pensivedog** [comment]
Looking forward to this!

**Comment by h-enk** [comment]
Tested/verified — solved/works with:

```json
  "otherDependencies": {
    "hugo": "0.123.7"
  },
```

**Comment by h-enk** [comment]
Closing
