### ISSUE TITLE
Paginated urls are added to list pages that don't use pagination

### ISSUE THREAD

**Issue by pensivedog** [gethyas/seo#4]
This is described in more detail on the Hugo community forum here:

https://discourse.gohugo.io/t/page-2-url-exists-where-it-shouldnt/45459

**Comment by pensivedog** [comment]
By calling `.Paginator`, this file is also interfering with attempts to filter pagination in list templates. See here for details:

https://discourse.gohugo.io/t/filtered-pagination-results-in-gaps/46051/7

**Comment by h-enk** [comment]
Closing — should no longer be an issue w/ new setup
