### ISSUE TITLE
Twitter summary card with large image

### ISSUE THREAD

**Issue by h-enk** [gethyas/seo#5]
### Discussed in https://github.com/orgs/gethyas/discussions/423

<div type='discussions-op-text'>

<sup>Originally posted by **pensivedog** August 31, 2023</sup>
No matter what I try, my pages always have `<meta name=twitter:card content="summary">` instead of `<meta name=twitter:card content="summary_large_image">`.

I have images set in front matter as an array, `images: ["img 1.jpg", img 2.jpg"]`. 

What am I doing wrong?</div>

Fix check: https://github.com/gethyas/seo/blob/main/layouts/partials/hugo-seo/private/params/twitter.html#L5

**Comment by pensivedog** [comment]
The file https://github.com/gethyas/seo/blob/main/layouts/partials/hugo-seo/private/params/images.html does not follow the same lookup rules as the [hugo internal template for twitter cards](https://gohugo.io/templates/internal/#twitter-cards), which searches for image page resources with feature, cover, or thumbnail in their name when there is not `images` array in front matter. 

It would be better if this module had a more robust way of searching for images.

It would be ideal if the front matter identifier for twitter card images could simply be configured in settings along with other seo module params.

**Comment by h-enk** [comment]
Fixed w/ new setup: [Twitter Cards](https://seo.gethyas.com/docs/built-ins/twitter-cards/)
