### ISSUE TITLE
Unable to use `where` with `Paginate` or `Paginator`

### ISSUE THREAD

**Issue by pensivedog** [gethyas/seo#7]
By calling `Paginator`, this file breaks `Paginate` or `Paginator` calls from layouts and list templates used in combination with `where`: 

https://github.com/gethyas/seo/blob/main/layouts/partials/hugo-seo/private/params/general.html#L109-L116

The problem is discussed in more detail on the Hugo support forum [here](https://discourse.gohugo.io/t/filtered-pagination-results-in-gaps/46051/7).

This file's usage of `Paginator` was brought up in [another issue](https://github.com/gethyas/seo/issues/4), but I thought it was worth opening a new issue since breaking the ability to use Hugo's `where` function with `Paginate` is a much bigger problem.

**Comment by h-enk** [comment]
I'm working on a new, more robust SEO module.

**Comment by h-enk** [comment]
Closing — should no longer be an issue w/ new setup
